/** @format */

import Footer from "@/components/Footer/Footer";
import '../globals.css'
import { Inter } from "next/font/google";
import SearchHeader from "@/components/SearchHeader/SearchHeader";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function SearchLayout({ children }) {
	return (
		<html lang='en'>
            <body className={inter.className}>
                <SearchHeader />
				{children}

				{/* footer  */}
				
			</body>
		</html>
	);
}
